### ISSUE TITLE
Can't tell if an item is selected or not on Windows Terminal

### ISSUE THREAD

**Issue by birtles** [yuki0418/bye-branch#1]
The tick appears purple whether or not the branch is selected.

This appears to be due to: https://github.com/microsoft/terminal/issues/13110

See also:
- https://github.com/microsoft/terminal/issues/15592
- https://github.com/console-rs/dialoguer/issues/264

PR forthcoming.

**Comment by yuki0418** [comment]
@birtles 

Thank you for the new issue!!
I will check it!!
